import { type CopilotToolKey, TASKS_WRITES } from "./tool-catalog";
import { LH_ALL_TOOL_KEYS } from "../tools/beam-api/learning-hub";
import {
  AGENT_TOOLS,
  ANALYTICS_TOOLS,
  GRAPH_TOOLS,
  INBOX_TOOLS,
  INTEGRATION_TOOLS,
  SEARCH_TOOLS,
  TASK_TOOLS,
  TEMPLATE_TOOLS,
  TRIGGER_TOOLS,
  USER_TOOLS,
  VIEW_TOOLS,
} from "./tool-keys";

export const AGENT_TASKS_TOOL_KEYS = [
  TASK_TOOLS.reads.GET_LATEST_EXECUTIONS,
  TASK_TOOLS.reads.LIST,
  TASK_TOOLS.reads.DETAIL,
  ANALYTICS_TOOLS.reads.AGENT,
  AGENT_TOOLS.reads.GET,
  GRAPH_TOOLS.reads.GET,
  GRAPH_TOOLS.reads.GET_NODES,
  GRAPH_TOOLS.reads.GET_NODE,
  GRAPH_TOOLS.reads.GET_HISTORY,
  AGENT_TOOLS.reads.SEARCH,
  ...TASKS_WRITES
] as const satisfies readonly CopilotToolKey[];

export const TASKS_GLOBAL_TOOL_KEYS = [
  TASK_TOOLS.reads.GET_STATUSES,
  TASK_TOOLS.reads.LIST_AGENTS,
  TASK_TOOLS.reads.LIST,
  TASK_TOOLS.reads.DETAIL,
  AGENT_TOOLS.reads.SEARCH,
  GRAPH_TOOLS.reads.GET,
  GRAPH_TOOLS.reads.GET_NODE,
  ...TASKS_WRITES
] as const satisfies readonly CopilotToolKey[];

export const AGENT_FLOW_READ_TOOL_KEYS = [
  AGENT_TOOLS.reads.GET,
  GRAPH_TOOLS.reads.GET,
  GRAPH_TOOLS.reads.GET_NODES,
  GRAPH_TOOLS.reads.GET_NODE,
  SEARCH_TOOLS.reads.VERIFY_LINKS,
  SEARCH_TOOLS.reads.TOOLS,
  TRIGGER_TOOLS.reads.LIST,
  TRIGGER_TOOLS.reads.ACTIONS,
  TRIGGER_TOOLS.reads.WEBHOOK,
  AGENT_TOOLS.reads.LIST_SUB_AGENTS,
  GRAPH_TOOLS.reads.GET_HISTORY,
  AGENT_TOOLS.reads.GET_TOOLS,
  AGENT_TOOLS.reads.LIST_CONTEXT_FILES,
  INTEGRATION_TOOLS.reads.LIST_CONNECTED,
  INTEGRATION_TOOLS.reads.IS_CONNECTED
] as const satisfies readonly CopilotToolKey[];

export const INTEGRATIONS_TOOL_KEYS = [
  INTEGRATION_TOOLS.reads.LIST,
  INTEGRATION_TOOLS.reads.LIST_CATEGORIES,
  INTEGRATION_TOOLS.reads.LIST_CONNECTED,
  INTEGRATION_TOOLS.reads.GET_CONNECTIONS,
  INTEGRATION_TOOLS.reads.IS_CONNECTED,
  TRIGGER_TOOLS.reads.ACTIONS,
  AGENT_TOOLS.reads.SEARCH,
  INTEGRATION_TOOLS.writes.CONNECT,
  INTEGRATION_TOOLS.writes.UPDATE_CONNECTION,
  INTEGRATION_TOOLS.writes.REMOVE_CONNECTION,
  INTEGRATION_TOOLS.writes.SET_DEFAULT,
  INTEGRATION_TOOLS.writes.REMOVE_CUSTOM,
  INTEGRATION_TOOLS.writes.CREATE_CUSTOM,
  INTEGRATION_TOOLS.writes.UPDATE_CUSTOM
] as const satisfies readonly CopilotToolKey[];

export const AGENT_CONFIG_TOOL_KEYS = [
  AGENT_TOOLS.reads.GET,
  AGENT_TOOLS.reads.GET_TOOLS,
  GRAPH_TOOLS.reads.GET_NODES,
  TRIGGER_TOOLS.reads.LIST,
  TRIGGER_TOOLS.reads.WEBHOOK,
  TRIGGER_TOOLS.reads.ACTIONS,
  AGENT_TOOLS.reads.LIST_SUB_AGENTS,
  AGENT_TOOLS.reads.LIST_CONTEXT_FILES,
  INTEGRATION_TOOLS.reads.LIST_CONNECTED,
  INTEGRATION_TOOLS.reads.IS_CONNECTED,
  AGENT_TOOLS.reads.SEARCH,
  AGENT_TOOLS.writes.UPDATE_METADATA,
  AGENT_TOOLS.writes.UPDATE_INTERFACE,
  AGENT_TOOLS.writes.DELETE,
  AGENT_TOOLS.writes.REMOVE_TOOLS,
  AGENT_TOOLS.writes.UPLOAD_CONTEXT_FILE,
  AGENT_TOOLS.writes.UPLOAD_EXTERNAL_FILE,
  AGENT_TOOLS.writes.TRANSCRIBE_AUDIO,
  AGENT_TOOLS.writes.DELETE_CONTEXT_FILE,
  AGENT_TOOLS.writes.DELETE_EXTERNAL_FILE,
  AGENT_TOOLS.writes.CHANGE_FILE_AGENT
] as const satisfies readonly CopilotToolKey[];

export const AGENT_ANALYTICS_TOOL_KEYS = [
  ANALYTICS_TOOLS.reads.AGENT,
  AGENT_TOOLS.reads.GET,
  AGENT_TOOLS.reads.SEARCH,
  TASK_TOOLS.reads.LIST,
  GRAPH_TOOLS.reads.GET_HISTORY,
  ANALYTICS_TOOLS.writes.EXPORT
] as const satisfies readonly CopilotToolKey[];

export const INBOX_TOOL_KEYS = [
  INBOX_TOOLS.reads.GET_UNREAD_COUNT,
  INBOX_TOOLS.reads.LIST_NOTIFICATIONS,
  TASK_TOOLS.reads.DETAIL,
  AGENT_TOOLS.reads.SEARCH,
  INBOX_TOOLS.writes.MARK_READ,
  INBOX_TOOLS.writes.DELETE,
  INBOX_TOOLS.writes.APPROVE_CONSENT,
  INBOX_TOOLS.writes.REJECT_CONSENT,
  INBOX_TOOLS.writes.SUBMIT_INPUT
] as const satisfies readonly CopilotToolKey[];

export const TEMPLATES_TOOL_KEYS = [
  TEMPLATE_TOOLS.reads.LIST_CATEGORIES,
  TEMPLATE_TOOLS.reads.GET_RECOMMENDATIONS,
  TEMPLATE_TOOLS.reads.LIST,
  TEMPLATE_TOOLS.reads.GET,
  TEMPLATE_TOOLS.reads.GET_WITH_PREREQS,
  SEARCH_TOOLS.reads.GLOBAL,
  AGENT_TOOLS.reads.SEARCH,
  TEMPLATE_TOOLS.writes.CREATE_AGENT_FROM
] as const satisfies readonly CopilotToolKey[];

export const VIEWS_TOOL_KEYS = [
  VIEW_TOOLS.reads.LIST,
  VIEW_TOOLS.reads.GET,
  VIEW_TOOLS.reads.LIST_RECORDS,
  VIEW_TOOLS.reads.LIST_LINKED_RECORDS,
  GRAPH_TOOLS.reads.GET_NODES,
  GRAPH_TOOLS.reads.GET_NODE,
  AGENT_TOOLS.reads.SEARCH,
  VIEW_TOOLS.writes.CREATE,
  VIEW_TOOLS.writes.DELETE,
  VIEW_TOOLS.writes.CREATE_COLUMN,
  VIEW_TOOLS.writes.UPDATE_COLUMN,
  VIEW_TOOLS.writes.DELETE_COLUMN,
  VIEW_TOOLS.writes.EXPORT_CSV
] as const satisfies readonly CopilotToolKey[];

export const LEARNING_HUB_TOOL_KEYS = [
  ...LH_ALL_TOOL_KEYS,
  AGENT_TOOLS.reads.GET,
  AGENT_TOOLS.reads.SEARCH,
  USER_TOOLS.reads.GET_CURRENT
] as const satisfies readonly CopilotToolKey[];
